lxtask: update to 0.1.10
This fixes link errors with gcc 10.

| ...ld: lxtask-callbacks.o:.../lxtask-0.1.9/src/interface.h:64: multiple definition of `column';
|        lxtask-main.o:.../lxtask-0.1.9/src/interface.h:64: first defined here

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>